### ISSUE TITLE
[Bug]: Add [id] to fillable property to allow mass assignment on [App\Models\User].

### ISSUE THREAD

**Issue by fcno** [noxoua/filament-activity-log#49]
### What happened?

I have a customized login screen (not sure if this is relevant), but when I use your package, it starts asking to release the User model ID for mass assignment.
I don't think it's a good option to do with a primary key.
Of course, without your package, everything works normally.
Do you have any idea why?

### How to reproduce the bug

As above

### Package Version

2.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by noxoua** [comment]
Could you share the error?

**Comment by fcno** [comment]
Hey man.

This is the full error log. Nothing special on My app and I just copy paste the code from your documentation changing the model name.


```
[2023-12-08 02:58:25] development.ERROR: Add [id] to fillable property to allow mass assignment on [App\Models\Usuario]. {"exception":"[object] (Illuminate\\Database\\Eloquent\\MassAssignmentException(code: 0): Add [id] to fillable property to allow mass assignment on [App\\Models\\Usuario]. at /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:524)
[stacktrace]
#0 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(613): Illuminate\\Database\\Eloquent\\Model->fill()
#1 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1537): Illuminate\\Database\\Eloquent\\Model->newInstance()
#2 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(158): Illuminate\\Database\\Eloquent\\Builder->newModelInstance()
#3 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->make()
#4 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#5 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\\Database\\Eloquent\\Model->__call()
#6 /dados/sites/sci/vendor/noxoua/filament-activity-log/src/ActivityLoggers.php(89): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#7 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(458): Noxo\\FilamentActivityLog\\ActivityLoggers::Noxo\\FilamentActivityLog\\{closure}()
#8 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#10 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#11 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1217): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#12 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#13 /dados/sites/sci/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(191): Illuminate\\Database\\Eloquent\\Model->save()
#14 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(438): LdapRecord\\Laravel\\Auth\\DatabaseUserProvider->validateCredentials()
#15 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Support/Timebox.php(32): Illuminate\\Auth\\SessionGuard->Illuminate\\Auth\\{closure}()
#16 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(447): Illuminate\\Support\\Timebox->call()
#17 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(386): Illuminate\\Auth\\SessionGuard->hasValidCredentials()
#18 /dados/sites/sci/vendor/filament/filament/src/Pages/Auth/Login.php(73): Illuminate\\Auth\\SessionGuard->attempt()
#19 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Pages\\Auth\\Login->authenticate()
#20 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /dados/sites/sci/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#24 /dados/sites/sci/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(465): Livewire\\Wrapped->__call()
#25 /dados/sites/sci/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(108): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#26 /dados/sites/sci/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#27 /dados/sites/sci/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(90): Livewire\\LivewireManager->update()
#28 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#29 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#30 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#31 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#32 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#33 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#35 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#37 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#39 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#41 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#42 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#44 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#48 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#49 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#50 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#51 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#52 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#53 /dados/sites/sci/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#55 /dados/sites/sci/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#57 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#59 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#63 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#67 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#69 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#71 /dados/sites/sci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /dados/sites/sci/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
```

**Comment by noxoua** [comment]
@fcno thanks for error. Can you upgrade package to the latest version?
